ListWords = [
    # ===== Tier S — melhores wake phrases =====
    "hey atlas",
    "ok atlas",
    "okay atlas",
    "hey atlas wake up",
    "ok atlas wake up",
    "atlas wake up",
    "hello atlas",
    "hi atlas",
    "hey atlas listen",
    "atlas listen",

    # ===== Tier A — muito boas =====
    "ei atlas",
    "olá atlas",
    "ola atlas",
    "fala atlas",
    "alô atlas",
    "alo atlas",
    "acorda atlas",
    "escuta atlas",
    "ouve atlas",
    "me ouve atlas",
    "chama atlas",
    "ativa atlas",
    "inicia atlas",
    "começa atlas",
    "atlas acorda",
    "atlas escuta",
    "atlas ouve",
    "atlas me ouve",
    "atlas responde",
    "atlas online",
    "atlas pronto",

    # ===== Tier B — boas =====
    "atlas agora",
    "atlas ativa",
    "atlas inicia",
    "atlas começa",
    "atlas bora",
    "atlas vamos lá",
    "atlas vamos la",
    "atlas pode começar",
    "atlas estou aqui",
    "atlas me ajuda",
    "atlas vem cá",
    "atlas vem ca",
    "atlas fala comigo",
    "atlas iniciar conversa",
    "atlas ligar",
    "atlas abrir",

    # ===== Tier C — aceitáveis =====
    "vamos atlas",
    "bora atlas",
    "atlas chamada",
    "atlas preciso de você",
    "atlas preciso de voce",

    # ===== Tier D — fracas / mais arriscadas =====
    "atlas",
]